name: Main project workflow

on:
  workflow_dispatch:
jobs:
  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  tsFormatCheck:
    name: check format ts
    uses: ./.github/workflows/ts_format_check_pipeline.yml

  kotlinTest:
    needs:
      - ktlintCheck
    name: test kotlin
    uses: ./.github/workflows/kotlin_test_pipeline.yml