
name: Main project workflow

on:
  push:
    branches:
      - main
      - develop
jobs:

  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  jacoco:
    needs:
      - ktlintCheck
    name: test and coverage kotlin
    uses: ./.github/workflows/kotlin_test_pipeline.yml