name: Run server tests

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DistributedCafe/DistributedCafeProject/.github/setupAction@server-add-menu
      - name: Run tests
        uses: DistributedCafe/DistributedCafeProject/.github/serverTest@server-add-menu